@startuml
!include Shared.puml


package "Product Catalog Context" {
  class Money
}

package "Anti-Corruption Layer" {
  Money --> Adapter
  class Adapter
}

package "Sales Context" {
  Adapter --> PreciseMoney
  interface PreciseMoney
  class PreciseEUR
  class PreciseUSD

  PreciseMoney <|-- PreciseEUR
  PreciseMoney <|-- PreciseUSD
}

package "Foreign Exchange Context" {
  PreciseMoney --> ConversionRate
  class ConversionRate
  interface ForeignExchange
  class WebAPIForeignExchange
  ForeignExchange <|--WebAPIForeignExchange
  ForeignExchange --> ConversionRate
}

package "Internal Financial Reporting" {
  ConversionRate --> RoundedEUR

  class RoundedEUR
}

@enduml