@startuml
!include Shared.puml


package "Product Catalog" {
  class Money
}

package "Anti-Corruption Layer" {
  Money --> Adapter
  class Adapter
}

package "Orders" {
  Adapter --> PreciseMoney
  interface PreciseMoney
  class PreciseEUR
  class PreciseUSD

  PreciseMoney <|-- PreciseEUR
  PreciseMoney <|-- PreciseUSD
}

package "Exchange" {
  PreciseMoney --> ConversionRate
  class ConversionRate
  interface Exchange
  class Adapter
  Exchange --> ConversionRate
}

package "Reporting" {
  ConversionRate --> RoundedEUR

  class RoundedEUR
}

@enduml