@startuml

!include Shared.puml


class PreciseMoney {
  +add(Money) : PreciseMoney
  +multiply(Number) : PreciseMoney
  +round() : RoundedMoney
}

class RoundedMoney {
   Constructor rounds the argument
   + getAmount() : Number
   + getCurrency() : Currency
}


PreciseMoney --> RoundedMoney : round to
note left of RoundedMoney
  No way back to
  PreciseMoney
end note


@enduml